### ISSUE TITLE
Issue after upgrading to .NET 6.0

### ISSUE THREAD

**Issue by olegkap** [koenbeuk/EntityFrameworkCore.Triggered#126] opened 2021-11-09 13:32 UTC
Hi,

After upgrading to .NET 6.0 I am getting this error when trying to run application or run dotnet ef tools.

`Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EntityFrameworkCore.Triggered, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e4acff2b88bee728' does not have an implementation.`

This was caused as a result of using `UseTriggers` which internally causes this issues.

Thanks,
Oleg

**Comment by koenbeuk** [comment] 2021-11-09 13:57
EF Core 6 has a breaking change. This project has a beta version out on NuGet that is compatible with EF Core 6. Please use version: v3.0.0-beta.3 for now and expect a proper V3 release later this month.

**Comment by koenbeuk** [comment] 2021-11-09 14:57
Closing this as a duplicate of: https://github.com/koenbeuk/EntityFrameworkCore.Triggered/issues/120

**Closed by koenbeuk** 2021-11-09 14:57 UTC
