### ISSUE TITLE
AfterSave trigger receives Entity = UnmodifiedEntity?

### ISSUE THREAD

**Issue by laurapetersen** [koenbeuk/EntityFrameworkCore.Triggered#92] opened 2021-01-28 12:50 UTC
Hi, I am trying the triggers and I'm noticing that the AfterSave trigger receives the updated/modified entity so I can't determine whether the fields I'm watching have changed.
Is this so or am I seeing this because another setting in my app, like LazyLoading?

**Comment by laurapetersen** [comment] 2021-01-28 13:28
I just verified that the BeforeSave trigger exhibits the same behavior.

**Comment by koenbeuk** [comment] 2021-01-28 17:41
For that we have an UnmodifiedEntity on the trigger context object, if you want to detect changes, you can use:
```csharp
 public Task AfterSave(ITriggerContext<Email> context, CancellationToken cancellationToken)
 {
       if (context.ChangeType == ChangeType.Modified && context.Entity.Title != context.UnmodifiedEntity.Title)
      {
           // Title has been updated....
      }
 }
```

This works the same for IBeforeSaveTriggers where context.Entity contains the new state of the Entity and context.UnmodifiedEntity contains the original state

Does that solve your issue?

**Comment by koenbeuk** [comment] 2021-01-28 18:43
I tried to reproduce this but was unable, given that the attached code ouputs:
```
Before save: name changed from foo to Bar
After save: name changed from foo to Bar
``` 
Which is what was expected, what version of EntityFrameworkCore.Triggered are you using?

```csharp
using var context = new MyDbContext();

context.Add(new Room { Id = Guid.NewGuid(), Persons = new List<Person> { new Person { Id = Guid.NewGuid(), Name = "foo" } } });
context.SaveChanges();
context.ChangeTracker.Clear();

var room = context.Rooms.Single();

var person = room.Persons.Single();
person.Name = "Bar";

context.SaveChanges();

public class Room { public Guid Id { get; set; } public virtual ICollection<Person> Persons { get; set; } }
public class Person { public Guid Id { get; set; } public string Name { get; set; } }

class PersonTrigger : IBeforeSaveTrigger<Person>, IAfterSaveTrigger<Person> {
    public Task BeforeSave(ITriggerContext<Person> context, CancellationToken cancellationToken) {
        if (context.ChangeType == ChangeType.Modified) {
            Console.WriteLine($"Before save: name changed from {context.UnmodifiedEntity.Name} to {context.Entity.Name}");
        }

        return Task.CompletedTask;
    }

    public Task AfterSave(ITriggerContext<Person> context, CancellationToken cancellationToken) {
        if (context.ChangeType == ChangeType.Modified) {
            Console.WriteLine($"After save: name changed from {context.UnmodifiedEntity.Name} to {context.Entity.Name}");
        }

        return Task.CompletedTask;
    }
}

class MyDbContext : DbContext {
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
        optionsBuilder
            .UseLazyLoadingProxies()
            .UseInMemoryDatabase(nameof(MyDbContext))
            .UseTriggers(triggerOptions =>
            {
                triggerOptions.AddTrigger<PersonTrigger>();
            });
    }

    public DbSet<Room> Rooms { get; set; }
}
```

**Comment by laurapetersen** [comment] 2021-02-05 14:46
Hi, thanks for the reply! I was able to look at this again today.
I'm using version 2.1.0 of the package. I've removed Lazy loading and I continue to see this behavior. My solution is using .Net 5.0

The triggers do not run when I add them like this:

            services.AddTriggeredDbContext<RferpContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DbConnection"),
                                                sqlServerOptions => sqlServerOptions.CommandTimeout(timeout))
                            .UseTriggers(triggerOptions =>
                            {
                                triggerOptions.AddTrigger<CustomerSaveTriggers>();
                            }));

but they do get hit when I add them as scoped:
            services.AddScoped<IBeforeSaveTrigger<Customer>, CustomerSaveTriggers>();
            services.AddScoped<IAfterSaveTrigger<Customer>, CustomerSaveTriggers>();

However, when they get hit and I inspect the context.Entity and context.UnmodifiedEntity they are the same.
This is in the BeforeSave trigger
![image](https://user-images.githubusercontent.com/12979053/107048378-a461bc00-67a7-11eb-8da3-eff3a71ee96e.png)

And I get exactly the same in the AfterSave trigger.

**Comment by koenbeuk** [comment] 2021-02-05 15:27
Transactions should not matter and the way you register your triggers (services.AddScoped<...>) is a supported approach. If possible, can you share  a sample project as I'm not able to reproduce the issue locally.

Alternatively, take a look at ChangeTrackers DebugView to ensure that your changes are actually present within EF, ie:

![image](https://user-images.githubusercontent.com/2912652/107053173-8036c700-6809-11eb-9d11-89cdf0971248.png)

Note how the ChangeTracker within my trigger indeed reveals that there is a name change. This correspondents with the state of Entity.Name and UnmodifiedEntity.Name

**Comment by koenbeuk** [comment] 2021-04-13 21:03
Going to close this issue as its stale. If you run into this issue, please try and use the latest version or otherwise feel free to reopen.

**Comment by MiguelMachadoCodeone** [comment] 2022-03-29 09:01
Hi, I have the same problem as @laurapetersen.

`UnmodifiedEntity `in `BeforeSave `and `AfterSave `always has the same values as `Entity`.

This is my trigger.

![image](https://user-images.githubusercontent.com/47603182/160574403-4c951894-3df4-47cf-adad-d2c948b8e4b4.png)

And this in one test endpoint that change only one property.

![image](https://user-images.githubusercontent.com/47603182/160574568-f68e9052-790f-4b68-85bb-0487a0f2ba29.png)

Declaration of Trigger in Startup:

![image](https://user-images.githubusercontent.com/47603182/160574755-2129a973-9594-40a3-9646-e0e8ef0c22d0.png)

Anyone could help?

**Comment by koenbeuk** [comment] 2022-03-29 16:41
@MiguelMachadoCodeone 

As I've not been able to reproduce this issue, can you try and follow the requested feedback as mentioned in this comment? https://github.com/koenbeuk/EntityFrameworkCore.Triggered/issues/92#issuecomment-774101462

Thanks!

**Comment by MiguelMachadoCodeone** [comment] 2022-03-30 08:37
Hi @koenbeuk, I try to do what you mention in your comment and my LongView is a bit different. I only have this:
`"Appointment {Id: 3634550} Modified`
`Id: 3634550 PK`
  `PlateNumber: 'LL-PP-11' Modified`
  `UpdatedAt: '30/03/2022 09:27:25' Modified"`
  
  LL-PP-11 is the new plateNumber I use in endpoint.
  
  This is my Trigger
  
  
![image](https://user-images.githubusercontent.com/47603182/160788432-aab28809-bd28-4666-92aa-4ed5cb5abb04.png)

And this is DataContext

![image](https://user-images.githubusercontent.com/47603182/160788902-df0a2e70-16cf-4066-ad38-f117cbd8915f.png)

**Comment by koenbeuk** [comment] 2022-03-30 10:54
@MiguelMachadoCodeone 

I think this is because of your call to `dbContext.Update(app);`. As it seems you have QueryTrackingBehavior configured as non-tracking, app wont be tracked until it has been modified (new plate number has been set). At that stage, EF is unaware of what the old plate number was and assumes that all properties should be marked as Modified. Things should start working when you either enable QueryTracking or attach the entity instead of updating, e.g.:

```csharp
dbContext.Attach(app); // By attaching (tracking) the entity before it mutates, EF can be aware of the original property values
app.PlateNumber = "xxx";
// dbContext.Update(app); // Calling update here would force update all properties, probably not what you want
dbContext.SaveChanges();
```

**Comment by koenbeuk** [comment] 2022-03-30 20:57
That depends, by tracking all, you do request more work from EF. Note that this is all happening in-memory so good chances are that you wont notice it. An advantage is that you update statements can be simpler as EF now knows what properties it needs to include whereas before it included all your properties.

You will have to run benchmarks in order to determine the actual impact.

**Comment by MiguelMachadoCodeone** [comment] 2022-03-31 08:54
Thanks @koenbeuk.

I will run some benchmarks to check performance.

**Closed** 2022-06-06 09:23 UTC
Labels: wontfix
